sudo: false
env:
  global:
    - secure: "BJScAQqZ93wF2MTL/52lsz9NN7einCoKC5SvdOzQ+MBGO6DOdEql3DqHPrys5xUHX0bejvdVbknS4GP5lRM+iv0+TF7jGz1FGCOA33WocOXMM7GxGAZq3Arnk9R2efNc0RplnF0kVQqOKa1hYtLmFCf9SZRltKCScewr1vKKf8k4R9egciSK+QTFZa+njCxFEVYJAOyifCukqcPRx1L7hJn2od0oaRctSRWhdWl8gPKAP4JLMdWqgmXEuDG3pTm8vq6JM2W7fhEXdlNr8P+txowGKBDw47m0LJc9q6ReH7FnqcpWMXdsIxGEeBd1nzvpqeNbBSKFwcEjqWKMqeImaySaVvSbcnLFZzU2MPb20sWRGiqP1oN8scQDnTG57hL/DeVY6gM7SFXZxD3akpvl865zNO9PlG4sCdANZv/ZEwSqAcMEQAXa32R1//iP+36HB6PHcNbDsi3o17/kfJRBnG7EFeLMfapyM1WiD5FJ39nS7MaLAIDFYus68J+VK/szpUjpL0623l2+RbmcQ660WGR+RV5mL/n6xtcCOTKnGRiVhvnYpqTAvU+jg2DBXlXWGTztZCqPoOHBtlVA+vwO7SYTl3W1/2ECPP6ogx6YRYjcasD/sj8Z8P8cbtpqSmPwR0D7J+vz+DX8qf01aG3NETcgGXhFq6i/WpRbUEXpK1U="
    - secure: "xO8U5JnHh+suRr0sSY7blEzyYPbO0SlzrMosKEq7Ohn3FBKV3FH51OfplG6vDI3FWs6q7mmTABsAnEq+ExypqOLPGno2xdEOs3isq0JV+OvoUVtSTyBE+DaM6kTEM7O1hLN361J+VKoKJ5c9SG9rv1+GtT2FNeONy86zC/nKyowe3ywMBUQBp+wm6g/OWsdsOlYm1n8f6U5E8AEdMWGuXe+BfjGsl1rUJdfLpl9H0Xyb7q1kFQcffZSls2vjmoTxvdmD3mLz6JsC+hBX3wGPD6929eC4puAffuTwFtlufJSvYYOYm36/gakzgpPATWlpCqXCKNUR/gj/dkesUcRqUJTKS0riy+7+OpeOI3y5UT+/bXuTA1+J/w6oRyg85jLMxrnSOBOV6kVQfbLHqSSmup2N/8chlPlAz66Cg7j4NqdZ9yvz9hQCgv0KzXmzefHcXqNrQ9tCSwbpO0xyItcHAXAuMRXk4mNeweIaisrXMbnnbclM5PVyRSpHDMwAURzxZ7bkw9qq4CH1gh6Uxso4ARy7aojItwZCJydUDDJqTx5BwooKcalIJzpExij+sBjTwjY6qAsb2cDiPJ4hS/pjMdmr9ZeN6JrfuVjMrqb2jHS9M0ZRfYm6KDLoR04ZPF/pOncWSs8DYft+6P+24hZ6AXvp2xlU5dYw+N6r+PPF4nY="

language: generic

matrix:
  include:
    - os: linux
      env: PYTHON="3.5"

    - os: linux
      env: PYTHON="3.6"

    - os: osx
      env: PYTHON="3.5"

    - os: osx
      env: PYTHON="3.6"

install:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      elif [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
        rvm get stable;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q --all
    - conda config --append channels conda-forge
    - if [[ -z "$TRAVIS_TAG" ]]; then
        sed -i -e "s/\${PYTHON}/"${PYTHON}"/" test-environment.yaml;
        conda env create -qf test-environment.yaml;
        source activate py${PYTHON};
      else
        if [[ "$PYTHON" == "3.6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
          conda env update -qn root -f build-environment.yaml;
        fi
      fi
      # Useful for debugging any issues with conda
    - conda info -a
    - conda list

# command to run tests
#script: pytest -vv --cov=./ && pylint pyked/
script:
  - set -e
  - if [[ -z "$TRAVIS_TAG" ]]; then
      python -m cProfile -o profile $(which pytest);
      python profile_code.py;
      if [[ "$PYTHON" == "3.6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
        git checkout -- test-environment.yaml;
        conda install -q sphinx doctr nbsphinx ipython;
        python setup.py install;
        cd docs;
        make html SPHINXOPTS="-W";
        cd ..;
        doctr deploy devel;
      fi
    else
      if [[ "$PYTHON" == "3.6" && "$TRAVIS_OS_NAME" == "linux" ]]; then
        conda build conda.recipe;
        anaconda -t $ANACONDA_TOKEN upload $HOME/miniconda/conda-bld/*/pyked*.tar.bz2;
        python setup.py install;
        cd docs;
        make html SPHINXOPTS="-W";
        cd ..;
        doctr deploy --no-require-master .;
      fi
    fi
  - set +e

after_success:
  - if [[ -z "$TRAVIS_TAG" ]]; then
      bash <(curl -s https://codecov.io/bash);
    fi

before_deploy:
  - conda install pandoc pypandoc

deploy:
  provider: pypi
  user: bryanwweber
  password:
    secure: "wvS+7cF9MCqkrFT34C7CeSgz6titZPzrqETex6M9MQL66zzC845BbMsTy+hEbk2yeowPkBwnboqrESXI/zpuGiICZTLxJspfCcNWeUy/fqssdFQ2oqFK26fS2rzLnJh5ipKd3rvlVnH2aX4txht9g8CnHxsr6ugU4Ik02JeBmRNAkC8tHffyLVQpkiX4CWudoYxNMxKiIu90Vv62ai52b0N6YMHENroIa3+pDivkJhF/NvwIu5uHsnAKh3X8Ftl5OFoEal5mr0qWQb0+gL8XporpZ0Zpo0fYElp/qF/mnCtsd2xRMuAE8sVVyt0QdfpPSwJJekTgzUWi7B0vUQ4eNQUm+MUcP6093ixTaNSg4suRr6Qq+zc+dRV1TKBvvnI9VDvqxkebIve2r02Fjw3T8iYOb6p1Jp/qK68xsGZXeG7FaVwNIIcyfOZFXWcl8pDQqH1cBONRGBrA7Itew5+dAUkbXzkcmr1e/VxBe3SMvJRiGSnnwstRho88zjYb9Q7R74SspPY8CBpmSEo1hZ495pF/IbP5T5awNW9qoH2AZlPLJqp5nUdJ16vJagdXmcct/f8jnMqAC/jp9myGqdentLjTLbyiSF4JNKYjtPKdnEM+U1KawXnMJMP95O4KgiI6GUxVQCYX/YV7OtJn0Ruaxdv9CDckcIJSktnJw53fH4Y="
  on:
    tags: true
    condition: $TRAVIS_OS_NAME == "linux" && $PYTHON == "3.6"
  distributions: "sdist bdist_wheel"
  skip_upload_docs: true
